version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "[%(asctime)s] [%(process)d] [%(levelname)s]: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S %z"

handlers:
  default:
    class: logging.StreamHandler
    formatter: default

loggers:
  uvicorn:
    level: INFO
    handlers: [default]
    propagate: False

  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: False

  uvicorn.access:
    level: INFO
    handlers: [default]
    propagate: False

root:
  level: INFO
  handlers: [default]
