interface EnsemblConcept implements Concept {
    prefix: ConceptPrefix!
    conceptId: String!
    label: String
    bioType: String
    start: Int
    end: Int
    sequence: String
    version: String
    strand: String
    source: String
    status: ConceptStatus!
    similarConcepts(threshold: Float): [SimilarEnsemblConcept!]!
    pathsTo(targetPrefix: ConceptPrefix!, targetConceptId: String!, relationship: RelationshipType!, direction: PathDirection = forward, maxDepth: Int = 12): [ConceptPath!]!
}

type EnsemblGene implements EnsemblConcept & Concept {
    prefix: ConceptPrefix!
    conceptId: String!
    label: String
    bioType: String
    start: Int
    end: Int
    sequence: String
    version: String
    strand: String
    source: String
    status: ConceptStatus!
    similarConcepts(threshold: Float): [SimilarEnsemblConcept!]!
    pathsTo(targetPrefix: ConceptPrefix!, targetConceptId: String!, relationship: RelationshipType!, direction: PathDirection = forward, maxDepth: Int = 12): [ConceptPath!]!
}

type EnsemblTranscript implements EnsemblConcept & Concept {
    prefix: ConceptPrefix!
    conceptId: String!
    label: String
    bioType: String
    start: Int
    end: Int
    sequence: String
    version: String
    strand: String
    source: String
    transcriptSupportLevel: String
    status: ConceptStatus!
    similarConcepts(threshold: Float): [SimilarEnsemblConcept!]!
    pathsTo(targetPrefix: ConceptPrefix!, targetConceptId: String!, relationship: RelationshipType!, direction: PathDirection = forward, maxDepth: Int = 12): [ConceptPath!]!
}

type EnsemblExon implements EnsemblConcept & Concept {
    prefix: ConceptPrefix!
    conceptId: String!
    label: String
    bioType: String
    start: Int
    end: Int
    sequence: String
    version: String
    strand: String
    source: String
    status: ConceptStatus!
    similarConcepts(threshold: Float): [SimilarEnsemblConcept!]!
    pathsTo(targetPrefix: ConceptPrefix!, targetConceptId: String!, relationship: RelationshipType!, direction: PathDirection = forward, maxDepth: Int = 12): [ConceptPath!]!
}

type EnsemblProtein implements EnsemblConcept & Concept {
    prefix: ConceptPrefix!
    conceptId: String!
    label: String
    bioType: String
    start: Int
    end: Int
    sequence: String
    version: String
    strand: String
    source: String
    status: ConceptStatus!
    similarConcepts(threshold: Float): [SimilarEnsemblConcept!]!
    pathsTo(targetPrefix: ConceptPrefix!, targetConceptId: String!, relationship: RelationshipType!, direction: PathDirection = forward, maxDepth: Int = 12): [ConceptPath!]!
}

type SimilarEnsemblConcept implements SimilarConcept {
    from: EnsemblConcept!
    to: EnsemblConcept!
    score: Float!
}

type EnsemblConceptResponse { error: QueryError, data: EnsemblConcept }
type EnsemblConceptListResponse { error: QueryError, data: [EnsemblConcept] }

type EnsemblQuery {
    ensemblConcept(conceptId: String!): EnsemblConceptResponse
    autoComplete(query: String!, limit: Int): EnsemblConceptListResponse
}

extend type Query { ensembl: EnsemblQuery }
